// Code generated by protoc-gen-go.
// source: api.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	Empty
	UserCreateType
	UserGetType
	User
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto1.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type UserCreateType struct {
	Age   uint32 `protobuf:"varint,1,opt,name=age" json:"age,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Name  string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Sex   string `protobuf:"bytes,4,opt,name=sex" json:"sex,omitempty"`
	Type_ string `protobuf:"bytes,5,opt,name=type_,json=type" json:"type_,omitempty"`
}

func (m *UserCreateType) Reset()                    { *m = UserCreateType{} }
func (m *UserCreateType) String() string            { return proto1.CompactTextString(m) }
func (*UserCreateType) ProtoMessage()               {}
func (*UserCreateType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type UserGetType struct {
	UserID int32 `protobuf:"varint,1,opt,name=userID" json:"userID,omitempty"`
}

func (m *UserGetType) Reset()                    { *m = UserGetType{} }
func (m *UserGetType) String() string            { return proto1.CompactTextString(m) }
func (*UserGetType) ProtoMessage()               {}
func (*UserGetType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type User struct {
	Age   uint32 `protobuf:"varint,1,opt,name=age" json:"age,omitempty"`
	Sex   string `protobuf:"bytes,2,opt,name=sex" json:"sex,omitempty"`
	Name  string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Email string `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto1.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto1.RegisterType((*Empty)(nil), "proto.Empty")
	proto1.RegisterType((*UserCreateType)(nil), "proto.UserCreateType")
	proto1.RegisterType((*UserGetType)(nil), "proto.UserGetType")
	proto1.RegisterType((*User)(nil), "proto.User")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for FilesService service

type FilesServiceClient interface {
}

type filesServiceClient struct {
	cc *grpc.ClientConn
}

func NewFilesServiceClient(cc *grpc.ClientConn) FilesServiceClient {
	return &filesServiceClient{cc}
}

// Server API for FilesService service

type FilesServiceServer interface {
}

func RegisterFilesServiceServer(s *grpc.Server, srv FilesServiceServer) {
	s.RegisterService(&_FilesService_serviceDesc, srv)
}

var _FilesService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.FilesService",
	HandlerType: (*FilesServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    fileDescriptor0,
}

// Client API for UserService service

type UserServiceClient interface {
	Create(ctx context.Context, in *UserCreateType, opts ...grpc.CallOption) (*Empty, error)
	Get(ctx context.Context, in *UserGetType, opts ...grpc.CallOption) (*User, error)
	List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (UserService_ListClient, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Create(ctx context.Context, in *UserCreateType, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/proto.UserService/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Get(ctx context.Context, in *UserGetType, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := grpc.Invoke(ctx, "/proto.UserService/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (UserService_ListClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_UserService_serviceDesc.Streams[0], c.cc, "/proto.UserService/List", opts...)
	if err != nil {
		return nil, err
	}
	x := &userServiceListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UserService_ListClient interface {
	Recv() (*User, error)
	grpc.ClientStream
}

type userServiceListClient struct {
	grpc.ClientStream
}

func (x *userServiceListClient) Recv() (*User, error) {
	m := new(User)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for UserService service

type UserServiceServer interface {
	Create(context.Context, *UserCreateType) (*Empty, error)
	Get(context.Context, *UserGetType) (*User, error)
	List(*Empty, UserService_ListServer) error
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCreateType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Create(ctx, req.(*UserCreateType))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGetType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Get(ctx, req.(*UserGetType))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserServiceServer).List(m, &userServiceListServer{stream})
}

type UserService_ListServer interface {
	Send(*User) error
	grpc.ServerStream
}

type userServiceListServer struct {
	grpc.ServerStream
}

func (x *userServiceListServer) Send(m *User) error {
	return x.ServerStream.SendMsg(m)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _UserService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _UserService_Get_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _UserService_List_Handler,
			ServerStreams: true,
		},
	},
	Metadata: fileDescriptor0,
}

func init() { proto1.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x50, 0xdb, 0x4a, 0x03, 0x31,
	0x14, 0x24, 0xdd, 0x64, 0xa5, 0xa7, 0xb5, 0xc8, 0xf1, 0x42, 0xe8, 0x53, 0x59, 0x51, 0xfa, 0x62,
	0x91, 0xfa, 0x09, 0x5e, 0x8a, 0xe0, 0xd3, 0x5a, 0x9f, 0x25, 0xca, 0x41, 0x02, 0x5d, 0x1b, 0x92,
	0x28, 0xee, 0x27, 0xf8, 0xd7, 0x92, 0x0b, 0x76, 0x17, 0xfa, 0x94, 0x99, 0x61, 0x0e, 0x33, 0x19,
	0x18, 0x2a, 0xa3, 0x17, 0xc6, 0x6e, 0xfd, 0x16, 0x45, 0x7c, 0xaa, 0x03, 0x10, 0xf7, 0x8d, 0xf1,
	0x6d, 0xe5, 0x60, 0xf2, 0xe2, 0xc8, 0xde, 0x5a, 0x52, 0x9e, 0xd6, 0xad, 0x21, 0x3c, 0x82, 0x42,
	0x7d, 0x90, 0x64, 0x33, 0x36, 0x3f, 0xac, 0x03, 0xc4, 0x13, 0x10, 0xd4, 0x28, 0xbd, 0x91, 0x83,
	0x19, 0x9b, 0x0f, 0xeb, 0x44, 0x10, 0x81, 0x7f, 0xaa, 0x86, 0x64, 0x11, 0xc5, 0x88, 0xc3, 0xad,
	0xa3, 0x1f, 0xc9, 0xa3, 0x14, 0x20, 0x1e, 0x83, 0xf0, 0xad, 0xa1, 0x57, 0x29, 0x92, 0x2d, 0x90,
	0xea, 0x02, 0x46, 0x21, 0x74, 0x45, 0x3e, 0x26, 0x9e, 0x41, 0xf9, 0xe5, 0xc8, 0x3e, 0xde, 0xc5,
	0x50, 0x51, 0x67, 0x56, 0xad, 0x81, 0x07, 0xdb, 0x9e, 0x46, 0x39, 0x67, 0xb0, 0xcb, 0xd9, 0xd7,
	0xe6, 0xbf, 0x37, 0xef, 0xf4, 0x5e, 0x4e, 0x60, 0xfc, 0xa0, 0x37, 0xe4, 0x9e, 0xc9, 0x7e, 0xeb,
	0x77, 0x5a, 0xfe, 0xb2, 0xd4, 0x26, 0x73, 0xbc, 0x82, 0x32, 0xad, 0x81, 0xa7, 0x69, 0xb3, 0x45,
	0x7f, 0xa0, 0xe9, 0x38, 0xcb, 0x71, 0x40, 0xbc, 0x84, 0x62, 0x45, 0x1e, 0xb1, 0xe3, 0xcd, 0xff,
	0x9a, 0x8e, 0x3a, 0x1a, 0x9e, 0x03, 0x7f, 0xd2, 0xce, 0x63, 0xef, 0xba, 0x67, 0xb9, 0x66, 0x6f,
	0x65, 0x64, 0x37, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9b, 0xdf, 0x14, 0x62, 0xb1, 0x01, 0x00,
	0x00,
}
